export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const STATUS_LOADING = 'STATUS_LOADING';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_ERRORS = 'STATUS_ERRORS';

